"use client";

import { FileText, Bot } from "lucide-react";
import { InsightSection } from "@/components/grounded/InsightSection";
import { ActionReviewPanel } from "@/components/grounded/ActionReviewPanel";
import { DisclaimerBox } from "@/components/grounded/DisclaimerBox";
import { useGenerateBrief } from "../../hooks";
import type { Investigation } from "../../types";

interface InvestigationBriefPanelProps {
  investigation: Investigation;
  canWrite: boolean;
}

export function InvestigationBriefPanel({
  investigation,
  canWrite,
}: InvestigationBriefPanelProps) {
  const briefMutation = useGenerateBrief(investigation.id);

  return (
    <InsightSection title="AI Investigation Brief" icon={FileText} iconColor="text-brand-600">
      {investigation.brief_summary ? (
        <div className="space-y-3">
          <div className="rounded-lg border border-navy-100 bg-navy-50 px-4 py-3">
            <div className="flex items-center gap-1.5 mb-2">
              <Bot size={12} className="text-brand-600" />
              <span className="text-[11px] font-medium text-brand-700">AI-Generated Brief</span>
            </div>
            <p className="text-sm text-navy-800 leading-relaxed">{investigation.brief_summary}</p>
          </div>
          <DisclaimerBox
            text="This brief was generated by AI. Verify all claims before using in official proceedings."
            compact
          />
          {canWrite && (
            <ActionReviewPanel
              title="Regenerate Brief"
              description="Generate a new brief from the latest evidence. The previous brief will be replaced."
              disclaimer="AI-generated briefs are decision-support tools only."
              actions={[
                {
                  label: briefMutation.isPending ? "Generating…" : "Regenerate",
                  variant: "secondary",
                  isLoading: briefMutation.isPending,
                  onClick: () => briefMutation.mutate(),
                },
              ]}
            />
          )}
        </div>
      ) : (
        <div className="space-y-3">
          <p className="text-xs text-navy-400">No brief generated yet.</p>
          {canWrite && (
            <ActionReviewPanel
              title="Generate AI Investigation Brief"
              description="The assistant will analyse all notes, related cases, linked offenders, and timeline events to produce a structured brief."
              disclaimer="AI briefs are decision-support only. You must review and approve before use in official documents."
              actions={[
                {
                  label: briefMutation.isPending ? "Generating…" : "Generate Brief",
                  variant: "primary",
                  isLoading: briefMutation.isPending,
                  onClick: () => briefMutation.mutate(),
                },
              ]}
            />
          )}
          {briefMutation.isError && (
            <p className="text-xs text-danger-600">{briefMutation.error?.message}</p>
          )}
        </div>
      )}
    </InsightSection>
  );
}
