import {
  BrainCircuit,
  Shield,
  TrendingUp,
  Network,
  Settings,
  BarChart3,
  MapPin,
  Users,
  BookOpen,
  Fingerprint,
  Activity,
  Wallet,
  Layers,
  Folder,
  AlertTriangle,
  Bell,
  FileText,
  Calendar,
  LineChart,
  AlertCircle,
  CheckSquare,
  Monitor,
  Map,
  Share2,
  MessageSquare,
  UserCog,
  Key,
  Database,
  Terminal,
  LayoutDashboard,
} from "lucide-react";
import type { NavGroup } from "@/types/navigation";

export const navGroups: NavGroup[] = [
  {
    id: "overview",
    label: "Overview",
    description: "Command center and district summary",
    icon: LayoutDashboard,
    items: [
      {
        title: "Dashboard",
        href: "/dashboard",
        description: "Command center: crime trends, alerts, and district overview",
        icon: LayoutDashboard,
        permission: "analytics.read",
      },
    ],
  },
  {
    id: "intelligence",
    label: "Intelligence",
    description: "Crime intelligence, offender profiles, and pattern analysis",
    icon: BrainCircuit,
    items: [
      {
        title: "Crime Analytics",
        href: "/dashboard",
        description: "District trends, category breakdowns, and summaries",
        icon: BarChart3,
        permission: "analytics.read",
      },
      {
        title: "Hotspots",
        href: "/map",
        description: "Geospatial hotspot intelligence and risk zones",
        icon: MapPin,
        permission: "analytics.read",
      },
      {
        title: "Offender Intelligence",
        href: "/offenders",
        description: "Repeat offenders, behavior profiles, and habitual patterns",
        icon: Users,
        permission: "criminology.read",
      },
      {
        title: "MO Patterns",
        href: "/mo-patterns",
        description: "Modus operandi extraction and similarity analysis",
        icon: Fingerprint,
        permission: "criminology.read",
      },
      {
        title: "Sociology Insights",
        href: "/sociology",
        description: "Social, environmental, and demographic risk factors",
        icon: BookOpen,
        permission: "sociology.read",
      },
      {
        title: "Financial Intelligence",
        href: "/financial",
        description: "Suspicious transactions, money trails, and financial patterns",
        icon: Wallet,
        permission: "analytics.read",
      },
      {
        title: "Cross-Intelligence Briefs",
        href: "/briefs",
        description: "Multi-source intelligence briefs for cases, offenders, districts",
        icon: Layers,
        permission: "analytics.read",
      },
    ],
  },
  {
    id: "operations",
    label: "Operations",
    description: "Active investigations, alerts, and audit trail",
    icon: Shield,
    items: [
      {
        title: "Investigations",
        href: "/investigations",
        description: "Open and closed investigation workspaces",
        icon: Folder,
        permission: "investigation.read",
      },
      {
        title: "Alerts",
        href: "/alerts",
        description: "Live crime alerts and triggered rule notifications",
        icon: AlertTriangle,
        permission: "alert.read",
      },
      {
        title: "Notifications",
        href: "/notifications",
        description: "System notifications and unread items",
        icon: Bell,
        permission: "notification.read",
      },
      {
        title: "Audit Logs",
        href: "/audit",
        description: "Full audit trail of system actions and decisions",
        icon: FileText,
        permission: "audit.read",
      },
    ],
  },
  {
    id: "forecast",
    label: "Forecasting",
    description: "Predictive intelligence and prevention recommendations",
    icon: TrendingUp,
    items: [
      {
        title: "Forecast Features",
        href: "/forecast/features",
        description: "Weekly crime feature windows and backtest history",
        icon: Calendar,
        permission: "forecast.read",
      },
      {
        title: "Crime Forecasts",
        href: "/forecast",
        description: "Projected crime volumes and hotspot risk scores",
        icon: LineChart,
        permission: "forecast.read",
      },
      {
        title: "Early Warnings",
        href: "/early-warnings",
        description: "Threshold-triggered decision-support warning signals",
        icon: AlertCircle,
        permission: "forecast.read",
      },
      {
        title: "Prevention Recommendations",
        href: "/prevention",
        description: "Reviewable prevention and policy recommendations",
        icon: CheckSquare,
        permission: "forecast.read",
      },
      {
        title: "Model Monitoring",
        href: "/monitoring",
        description: "Forecast quality, drift metrics, and data freshness",
        icon: Monitor,
        permission: "forecast.read",
      },
    ],
  },
  {
    id: "visualization",
    label: "Visualization",
    description: "Maps, graphs, and relationship networks",
    icon: Network,
    items: [
      {
        title: "Map View",
        href: "/map",
        description: "Geospatial crime distribution and hotspot overlay",
        icon: Map,
        permission: "analytics.read",
      },
      {
        title: "Graph View",
        href: "/graph",
        description: "Relationship graph between offenders, cases, and locations",
        icon: Network,
        permission: "analytics.read",
      },
      {
        title: "Expanded Network",
        href: "/network",
        description: "Suspected organized group candidates and associations",
        icon: Share2,
        permission: "analytics.read",
      },
    ],
  },
  {
    id: "assistant",
    label: "Assistant",
    description: "AI-powered investigation assistant",
    icon: MessageSquare,
    items: [
      {
        title: "AI Assistant",
        href: "/assistant",
        description: "Natural language intelligence queries and investigation help",
        icon: MessageSquare,
        permission: "assistant.use",
      },
    ],
  },
  {
    id: "admin",
    label: "Admin",
    description: "Governance, deployment, and system configuration",
    icon: Settings,
    items: [
      {
        title: "Governance Hub",
        href: "/admin",
        description: "Governance overview and system KPIs dashboard",
        icon: LayoutDashboard,
        permission: "admin.manage_users",
      },
      {
        title: "Audit Logs",
        href: "/admin/audit-logs",
        description: "Full audit trail of administrative actions",
        icon: FileText,
        permission: "audit.read",
      },
      {
        title: "User Management",
        href: "/admin/users",
        description: "Manage system operators and jurisdictions",
        icon: UserCog,
        permission: "admin.manage_users",
      },
      {
        title: "Roles & Permissions",
        href: "/admin/roles",
        description: "Cross-reference RBAC permission matrices",
        icon: Key,
        permission: "admin.manage_users",
      },
      {
        title: "System Health",
        href: "/admin/system-health",
        description: "Verify API and WebSocket connection health",
        icon: Activity,
        permission: "admin.manage_users",
      },
      {
        title: "Data Governance",
        href: "/admin/data-governance",
        description: "Review safety policies and disclaimers",
        icon: Shield,
        permission: "admin.manage_users",
      },
      {
        title: "Admin Jobs",
        href: "/admin/jobs",
        description: "Run and monitor pipeline admin jobs",
        icon: Terminal,
        permission: "admin.run_jobs",
      },
      {
        title: "Model Registry",
        href: "/admin/system",
        description: "Active ML model registrations and metadata",
        icon: Database,
        permission: "admin.manage_users",
      },
    ],
  },
];
